# Generated by Django 4.1.5 on 2023-01-31 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_team', models.CharField(max_length=50)),
                ('guest_team', models.CharField(max_length=50)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('host_score', models.IntegerField(max_length=100)),
                ('guest_score', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('skill_level', models.IntegerField(max_length=10)),
                ('set_of_injury', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('coach', models.CharField(max_length=200)),
                ('captain', models.CharField(max_length=200)),
                ('set_of_players', models.IntegerField(max_length=50)),
            ],
        ),
    ]
